---
- name: BitWarden | Compose the containers
  docker_compose:
    project_name: 'bitwarden'
    project_src: '{{ bitwarden_stub_path }}/docker'
    pull: true
    state: present
    recreate: '{{ cont_recreate }}'
    restarted:  '{{ cont_restart }}'
