---
- name: BitWarden | Set UID & GID for containers
  copy:
    dest: '{{ bitwarden_stub_path }}/env/uid.env'
    mode: 0644
    owner: '{{ bitwarden_owner }}'
    group: '{{ bitwarden_group }}'
    content: |
      LOCAL_UID={{ bitwarden_container_uid }}
      LOCAL_GID={{ bitwarden_container_gid }}

- name: BitWarden | Compose the containers
  command: docker-compose -f ./docker/docker-compose.yml up -d
  args:
    chdir: '{{ bitwarden_stub_path }}'
