---
- name: BitWarden | Generate Global configuration
  template:
    path: '{{ bitwarden_stub_path }}/env/global.override.env'
    src: 'config.j2'
    mode: 0600
    force: true
  vars:
    values_dict: '{{ bitwarden_global_settings }}'

- name: BitWarden | Generate MSSQL configuration
  template:
    path: '{{ bitwarden_stub_path }}/env/mssql.override.env'
    src: 'config.j2'
    mode: 0600
    force: true
  vars:
    values_dict: '{{ bitwarden_mssql_settings }}'

- name: BitWarden | Generate Docker configuration
  template:
    path: '{{ bitwarden_stub_path }}/docker/global.env'
    src: 'config.j2'
    mode: 0600
    force: true
  vars:
    values_dict: '{{ bitwarden_docker_settings }}'

- name: BitWarden | Generate Proxy configuration
  template:
    path: '{{ bitwarden_stub_path }}/nginx/default.conf'
    src: 'nginx.conf.j2'
    mode: 0644
    force: true
  vars:
    values_dict: '{{ bitwarden_docker_settings }}'

- name: BitWarden | Adjust Docker Compose Proxy ports
  replace:
    path: '{{ bitwarden_stub_path }}/docker/docker-compose.yml'
    regexp: '80:8080'
    replace: '{{ bitwarden_proxy_port }}:{{ bitwarden_proxy_port }}'

- name: BitWarden | Adjust App configuration
  replace:
    path: '{{ bitwarden_stub_path }}/web/app-id.json'
    regexp: 'bitwarden\.example\.com'
    replace: '{{ bitwarden_domain }}'
