---
- name: BitWarden | Generate Global configuration
  template:
    src: 'global.override.env.j2'
    dest: '{{ bitwarden_stub_path }}/env/global.override.env'
    mode: 0600
    owner: '{{ bitwarden_owner }}'
    group: '{{ bitwarden_group }}'
    force: true

- name: BitWarden | Generate MSSQL configuration
  template:
    dest: '{{ bitwarden_stub_path }}/env/mssql.override.env'
    src: 'mssql.override.env.j2'
    mode: 0600
    owner: '{{ bitwarden_owner }}'
    group: '{{ bitwarden_group }}'
    force: true
  vars:
    values_dict: '{{ bitwarden_mssql_settings }}'

- name: BitWarden | Adjust App configuration
  replace:
    path: '{{ bitwarden_stub_path }}/web/app-id.json'
    regexp: 'bitwarden\.example\.com'
    replace: '{{ bitwarden_domain }}'
