---
- name: BitWarden | Create the directory for certificates
  file:
    path: '{{ bitwarden_stub_path }}/ssl/{{ bitwarden_domain }}'
    owner: '{{ bitwarden_owner }}'
    group: '{{ bitwarden_group }}'
    state: directory

- name: BitWarden | Copy over SSL Private Key
  copy:
    dest: '{{ bitwarden_stub_path }}/ssl/{{ bitwarden_domain }}/private.key'
    content: '{{ bitwarden_ssl_private_key }}'
    owner: '{{ bitwarden_owner }}'
    group: '{{ bitwarden_group }}'

- name: BitWarden | Copy over SSL Cretificate
  copy:
    dest: '{{ bitwarden_stub_path }}/ssl/{{ bitwarden_domain }}/certificate.crt'
    content: '{{ bitwarden_ssl_certificate }}'
    owner: '{{ bitwarden_owner }}'
    group: '{{ bitwarden_group }}'

- name: BitWarden | Copy over SSL Certificate Authority
  copy:
    dest: '{{ bitwarden_stub_path }}/ssl/{{ bitwarden_domain }}/ca.crt'
    content: '{{ bitwarden_ssl_cert_authority }}'
    owner: '{{ bitwarden_owner }}'
    group: '{{ bitwarden_group }}'

- name: BitWarden | Fix Nginx config to use correct domain
  replace:
    path: '{{ bitwarden_stub_path }}/nginx/default.conf'
    regexp: 'bitwarden\.example\.com'
    replace: '{{ bitwarden_domain }}'
